---
title: "Paper"
format: html
editor: visual
---

## Paper

	In our modern political landscape, media and advertisements play a crucial role in shaping public opinion and influencing voting behavior. As digital platforms continue to progress, political messaging has been able to expand beyond typical media sources and has progressed into the social media feeds of millions of Americans. This project explores the impact of forms of political media, particularly digital advertisements and social media posts, on voting behavior and turnout. By analyzing the rise in political advertising and online political content surrounding major election dates, we aim to assess how these efforts appeal to different generations of voters and ultimately affect their engagement in the democratic process.

	To carry out this investigation, we plan to utilize publicly available datasets from Google, Facebook, and X, which provide detailed information on political ad spending and social media activity. We plan to compare political ad spending across states and analyze corresponding voter turnouts during the 2016 and 2020 presidential elections. We will also analyze the frequency and content of political social media posts in the weeks leading up to the election, with particular attention to the notable increase in activity as election day approaches. While our primary focus is on identifying trends in political media volume and timing, we also will consider how these patterns may relate to broader changes in voter behavior across generations – particularly among younger users who are more likely to engage with content on social media.
